- name: Add Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: grafana

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
    state: present

- name: Ensure Grafana is enabled and started
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Wait for Grafana to start
  wait_for:
    port: 3000
    delay: 5
    timeout: 30

- name: Configure Prometheus datasource in Grafana
  uri:
    url: "http://{{ ansible_host }}:3000/api/datasources"
    method: POST
    user: admin
    password: admin
    force_basic_auth: yes
    status_code: 200,409
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ ansible_host }}:9090
      isDefault: true
